import { Modifier, Rotation, Stance } from "./trick-options";

export type BotTrickData = {
  stanceRates: Partial<Record<Stance, number>>;
  rotationModifiers: Partial<Record<Rotation, number>>;
  modifierPenalties: Partial<Record<Modifier, number>>;
};

export type BotTrickSet = Record<string, BotTrickData>;

export type DifficultyPools = {
  Easy: BotTrickSet;
  Medium: BotTrickSet;
  Hard: BotTrickSet;
  Custom: BotTrickSet;
};

export const BOT_TRICKS: DifficultyPools = {
  Easy: {
    // Direction-optional tricks (bare entry will be generated by pool builder)
    ollie: {
      stanceRates: { regular: 0.6, fakie: 0.6 },
      rotationModifiers: { "BS 180": 0.65, "FS 180": 0.65 },
      modifierPenalties: { "body varial": 0.5 },
    },
    kickflip: {
      stanceRates: { regular: 0.25, fakie: 0.2 },
      rotationModifiers: {},
      modifierPenalties: { "body varial": 0.2 },
    },
    heelflip: {
      stanceRates: { regular: 0.25, fakie: 0.2 },
      rotationModifiers: {},
      modifierPenalties: { "body varial": 0.2 },
    },

    // Direction-required tricks (bare entry will NOT be generated by pool builder)
    shuvit: {
      stanceRates: { regular: 0.46, fakie: 0.46, nollie: 0.48 },
      rotationModifiers: { BS: 1.0, FS: 0.9 },
      modifierPenalties: { late: 0.3, "body varial": 0.4, revert: 0.3 },
    },
  },

  Medium: {
    // Direction-optional tricks
    ollie: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: {
        "BS 180": 0.0,
        "FS 180": 0.0,
        "BS 360": 0.0,
        "FS 360": 0.0,
      },
      modifierPenalties: { "body varial": 0.0 },
    },
    kickflip: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { "BS 180": 0.0, "FS 180": 0.0 },
      modifierPenalties: { late: 0.0, "body varial": 0.0 },
    },
    heelflip: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { "BS 180": 0.0, "FS 180": 0.0 },
      modifierPenalties: { late: 0.0, "body varial": 0.0 },
    },
    "varial flip": {
      stanceRates: { regular: 0.0, fakie: 0.0 },
      rotationModifiers: {},
      modifierPenalties: { late: 0.0, revert: 0.0 },
    },
    "varial heel": {
      stanceRates: { regular: 0.0, fakie: 0.0 },
      rotationModifiers: {},
      modifierPenalties: { late: 0.0, revert: 0.0 },
    },

    // Direction-required tricks
    shuvit: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { BS: 0.0, FS: 0.0 },
      modifierPenalties: { late: 0.0, "body varial": 0.0, revert: 0.0 },
    },
    "360 shuvit": {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { BS: 0.0, FS: 0.0 },
      modifierPenalties: { late: 0.0, "body varial": 0.0, revert: 0.0 },
    },
    bigspin: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0 },
      rotationModifiers: { BS: 0.0, FS: 0.0 },
      modifierPenalties: { late: 0.0, "body varial": 0.0 },
    },
  },

  Hard: {
    // Direction-optional tricks
    ollie: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: {
        "BS 180": 0.0,
        "FS 180": 0.0,
        "BS 360": 0.0,
        "FS 360": 0.0,
      },
      modifierPenalties: { "body varial": 0.0 },
    },
    kickflip: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: {
        "BS 180": 0.0,
        "FS 180": 0.0,
        "BS 360": 0.0,
        "FS 360": 0.0,
      },
      modifierPenalties: { late: 0.0, pressure: 0.0, "body varial": 0.0 },
    },
    heelflip: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: {
        "BS 180": 0.0,
        "FS 180": 0.0,
        "BS 360": 0.0,
        "FS 360": 0.0,
      },
      modifierPenalties: { late: 0.0, pressure: 0.0, "body varial": 0.0 },
    },
    "varial flip": {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: {},
      modifierPenalties: { late: 0.0, pressure: 0.0, revert: 0.0 },
    },
    "varial heel": {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: {},
      modifierPenalties: { late: 0.0, pressure: 0.0, revert: 0.0 },
    },
    hardflip: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { "BS 180": 0.0, "FS 180": 0.0 },
      modifierPenalties: { late: 0.0, pressure: 0.0, revert: 0.0 },
    },
    "inward heel": {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { "BS 180": 0.0, "FS 180": 0.0 },
      modifierPenalties: { late: 0.0, pressure: 0.0, revert: 0.0 },
    },
    "tre flip": {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: {},
      modifierPenalties: { pressure: 0.0, revert: 0.0 },
    },
    "laser flip": {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: {},
      modifierPenalties: { pressure: 0.0, revert: 0.0 },
    },

    // Direction-required tricks
    shuvit: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { BS: 0.0, FS: 0.0 },
      modifierPenalties: { late: 0.0, "body varial": 0.0, revert: 0.0 },
    },
    "360 shuvit": {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { BS: 0.0, FS: 0.0 },
      modifierPenalties: { late: 0.0, "body varial": 0.0, revert: 0.0 },
    },
    bigspin: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { BS: 0.0, FS: 0.0 },
      modifierPenalties: { late: 0.0, "body varial": 0.0 },
    },
    biggerspin: {
      stanceRates: { regular: 0.0, fakie: 0.0, nollie: 0.0, switch: 0.0 },
      rotationModifiers: { BS: 0.0, FS: 0.0 },
      modifierPenalties: { revert: 0.0 },
    },
  },

  // Custom is intentionally empty — populated at runtime by the user
  Custom: {},
};
